bids_dir: '../hippunfold_highresT2/hippunfold' # only used if custom_path is not provided below for each file
participant_label: 
  - '7607477'


segs:
  hippunfoldT1:
    path: &defaultseg
      '../hippunfold_atlasfix/hippunfold/sub-{subject}/anat/sub-{subject}_hemi-{hemi}_space-cropT2w_desc-subfields_atlas-bigbrain_dseg.nii.gz'  
    lut: 'resources/hippunfold.lut'
    hemi_convert: #needs to be here even if no change
      L: L
      R: R
  ashs: 
    path: '../ashs/sub-{subject}/final/{subject}_{hemi}_lfseg_corr_nogray.nii.gz'
    lut: 'resources/ashs.lut'
    hemi_convert:
      L: left
      R: right
  freesurfer: 
    path: '../freesurfer/sub-{subject}/mri/{hemi}.hippoAmygLabels-T2.v21.FS60.space-T2w.nii.gz'
    lut: 'resources/freesurfer.lut'
    hemi_convert:
      L: lh
      R: rh
  


pybids_inputs:
  mri: 
    filters:
      suffix: 'T2w'
      extension: '.nii.gz'
      datatype: 'anat'
    wildcards:
      - subject
      - session
    custom_path:
      '../hippunfold_highresT2/hippunfold/sub-{subject}/anat/sub-{subject}_desc-preproc_T2w.nii.gz'
  seg: 
    filters:
      suffix: 'dseg'  #note, bids filters are not used if custom_path is included
      extension: '.nii.gz'
      datatype: 'anat'
    wildcards:
      - subject
      - session
      - hemi
    custom_path: *defaultseg


# we use np.linspace to get the slices to use
#start and stop are in "voxels", relative to the centroid of the entire segmentation (voxel space of the segmentation)
#slices are integers

#ideally would want extents of segmentation, and just pick number of slices --

opacity: '100'
size: '200 150'
displayrange_percentiles: '5 95'


slice_montages:
  coronal:
    axis: 'y'
    zoom: 2200
    start: -30
    stop: +30
    slices: 5
  sagittal:
    axis: 'x'
    zoom: 2000
    start: -30
    stop: +30
    slices: 5
  axial:
    axis: 'z'
    zoom: 1800
    start: -30
    stop: +30
    slices: 5

